services:
  api:
    image: ghcr.io/naknao-nnct/gh-runner-controller-docker:latest  # production
    # build: .  # development
    restart: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
